version: '3.1'

services:
  bot:
    build: .
    depends_on:
      - postgres
    command: npm run dev
    volumes:
      - ./src:/usr/src/app/src

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: peer2peer
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
